Add shellcheck & apply compat fixes

diff --git a/bin/dotfiles b/bin/dotfiles
--- a/bin/dotfiles
+++ b/bin/dotfiles
@@ -23,7 +23,7 @@ sub_edit () {
 }
 
 sub_reload () {
-    source ~/.bash_profile && echo "Bash reloaded."
+    . ~/.bash_profile && echo "Bash reloaded."
 }
 
 sub_update () {
@@ -40,18 +40,18 @@ sub_update () {
 
 sub_osx () {
     for DEFAULTS_FILE in "$DOTFILES_DIR"/osx/defaults*.sh; do
-        [ -f "$DEFAULTS_FILE" ] && echo "Applying $DEFAULTS_FILE" && source "$DEFAULTS_FILE"
+        [ -f "$DEFAULTS_FILE" ] && echo "Applying $DEFAULTS_FILE" && . "$DEFAULTS_FILE"
     done
     echo "Done. Some changes may require a logout/restart to take effect."
 }
 
 sub_dock () {
-    source "$DOTFILES_DIR/osx/dock.sh" && echo "Dock reloaded."
+    . "$DOTFILES_DIR/osx/dock.sh" && echo "Dock reloaded."
 }
 
 sub_install () {
     local SCRIPT="${DOTFILES_DIR}/install/${SUB_COMMAND_NAME}.sh"
-    [ -f "$SCRIPT" ] && source "$SCRIPT" || echo "Unable to find script to install ${SUB_COMMAND_NAME}"
+    [ -f "$SCRIPT" ] && . "$SCRIPT" || echo "Unable to find script to install ${SUB_COMMAND_NAME}"
 }
 
 # Make sure to keep this in sync with the available public commands
