Install script all the things

diff --git a/bin/dotfiles b/bin/dotfiles
--- a/bin/dotfiles
+++ b/bin/dotfiles
@@ -2,16 +2,20 @@
 
 BIN_NAME=$(basename $0)
 COMMAND_NAME=$1
+SUB_COMMAND_NAME=$2
 
 sub_help () {
     echo "Usage: $BIN_NAME <command>\n"
     echo "Commands:"
-    echo "   help        This help message"
-    echo "   edit        Open dotfiles in default editor ($EDITOR) and Git GUI ($GIT_GUI)"
-    echo "   reload      Reload dotfiles"
-    echo "   update      Update OS X Applications, Homebrew (cask), npm, and Ruby packages"
-    echo "   osx         Apply OS X system defaults"
-    echo "   dock        Apply OS X Dock settings"
+    echo "   help               This help message"
+    echo "   edit               Open dotfiles in default editor ($EDITOR) and Git GUI ($GIT_GUI)"
+    echo "   reload             Reload dotfiles"
+    echo "   update             Update OS X Applications, Homebrew (cask), npm, and Ruby packages"
+    echo "   osx                Apply OS X system defaults"
+    echo "   dock               Apply OS X Dock settings"
+    echo "   install bash       Install Bash (Homebrew)"
+    echo "   install mjolnir    Install Mjolnir (Homebrew/Luarocks)"
+    echo "   install vundle     Install Vundle"
 }
 
 sub_edit () {
@@ -43,10 +47,15 @@ sub_dock () {
     source "$DOTFILES_DIR/osx/dock.sh" && echo "Dock reloaded."
 }
 
+sub_install () {
+    local SCRIPT="${DOTFILES_DIR}/install/${SUB_COMMAND_NAME}.sh"
+    [ -f "$SCRIPT" ] && source "$SCRIPT" || echo "Unable to find script to install ${SUB_COMMAND_NAME}"
+}
+
 # Make sure to keep this in sync with the available public commands
 
 sub_completion () {
-    echo "help edit reload update osx dock"
+    echo "help edit reload update osx dock install"
 }
 
 case $COMMAND_NAME in
